name: Build Go

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # https://www.lifewire.com/fix-developer-cannot-be-verified-error-5183898
          # - macos-latest
        include:
          - os: ubuntu-latest
            binary_name: clean-links
          - os: windows-latest
            binary_name: clean-links.exe
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      - id: lower-runner-os
        run: |
          LOWER_RUNNER_OS=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          echo "Set LOWER_RUNNER_OS to $LOWER_RUNNER_OS"

          echo "LOWER_RUNNER_OS=$LOWER_RUNNER_OS" >> "$GITHUB_ENV"
          echo "LOWER_RUNNER_OS=$LOWER_RUNNER_OS" >> "$GITHUB_OUTPUT"

      - run: |
          go build -ldflags "-s -w" -o ${{ matrix.binary_name }}
          TGZ_NAME="clean-links-$LOWER_RUNNER_OS.tgz"
          tar czf $TGZ_NAME ${{ matrix.binary_name }} LICENSE README.md
        env:
          CGO_ENABLED: 0

      - uses: actions/upload-artifact@v3
        with:
          name: clean-links-${{ steps.lower-runner-os.outputs.LOWER_RUNNER_OS }}
          path: "clean-links-*.tgz"
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./**/clean-links-*.tgz"
